-- -- lua/lsp/ls.lua
--   require('lspconfig').lua_ls.setup({
--     settings = {
--       Lua = {
--         telemetry = {
--           enable = false
--         },
--       },
--     },
--     on_init = function(client)
--       local join = vim.fs.joinpath
--       local path = client.workspace_folders[1].name

--       -- Check for local configuration files
--       if vim.uv.fs_stat(join(path, '.luarc.json'))
--         or vim.uv.fs_stat(join(path, '.luarc.jsonc'))
--       then
--         return
--       end

--       -- Neovim-specific settings
--       local runtime_path = vim.split(package.path, ';')
--       table.insert(runtime_path, join('lua', '?.lua'))
--       table.insert(runtime_path, join('lua', '?', 'init.lua'))

--       local nvim_settings = {
--         runtime = {
--           version = 'LuaJIT',
--           path = runtime_path
--         },
--         diagnostics = {
--           globals = {'vim'}
--         },
--         workspace = {
--           checkThirdParty = false,
--           library = {
--             vim.env.VIMRUNTIME,
--             vim.fn.stdpath('config'),
--           },
--         },
--       }

--       client.config.settings.Lua = vim.tbl_deep_extend(
--         'force',
--         client.config.settings.Lua,
--         nvim_settings
--       )
--     end,
--   })
