return {
  cmp = {
    nvim_lsp = '👾',
    buffer = '📝',
    path = '💽',
    tmux = '💻',
    copilot = '🚀',
  },
  diagnostics = {
    Error = '🔥',
    Warn = '💩',
    Hint = '👾',
    Info = '🧠',
  },
  lazy = {
    cmd = '⌘',
    config = '🛠',
    event = '📅',
    ft = '📂',
    init = '⚙️',
    keys = '🗝',
    plugin = '🔌',
    runtime = '💻',
    require = '🌙',
    source = '📄',
    start = '🚀',
    task = '📌',
    lazy = '💤',
  },
}
